# Generated by Django 4.1.4 on 2023-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(max_length=200)),
                ('descriptiong', models.TextField()),
                ('parameter', models.CharField(choices=[('kg', 'kg'), ('ltr', 'ltr'), ('mtr', 'mtr')], max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('Avaliable', models.BooleanField(default=True)),
            ],
        ),
    ]
