# Generated by Django 4.1.4 on 2023-01-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('parameter', models.CharField(choices=[('kg', 'kg'), ('ltr', 'ltr'), ('mtr', 'mtr')], max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('Avaliable', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.AddField(
            model_name='products',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers'),
        ),
    ]
